apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: brewsource-mcp-dev

namespace: brewsource-dev

resources:
  - ../base

labels:
  - pairs:
      environment: development

patches:
  - path: patches/brewsource-dev.yaml
  - path: patches/postgres-dev.yaml

configMapGenerator:
  - name: brewsource-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug
      - DATABASE_URL=postgres://brewsource_user:brewsource_pass@postgres:5432/brewsource_dev?sslmode=disable
