---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
  # Default development credentials (base64 encoded)
  # POSTGRES_USER: brewsource_user
  # POSTGRES_PASSWORD: devpassword123
  POSTGRES_USER: YnJld3NvdXJjZV91c2Vy
  POSTGRES_PASSWORD: ZGV2cGFzc3dvcmQxMjM=
