# Play 1: Provision the K3s server on the remote node
- name: Configure K3s Server
  hosts: k3s_server
  become: yes
  tasks:
    - name: Download K3s installation script
      get_url:
        url: https://get.k8s.io
        dest: /tmp/install_k3s.sh
        mode: '0755'

    - name: Run K3s installation script
      command: /tmp/install_k3s.sh
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for K3s API server to be ready
      wait_for:
        path: /etc/rancher/k3s/k3s.yaml

    - name: Fetch the Kubeconfig file from the server
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ playbook_dir }}/k3s_config"
        flat: yes

    - name: Open required ports in firewall
      become: true
      ansible.builtin.shell: |
        firewall-cmd --add-port=6443/tcp --zone=public --permanent
        firewall-cmd --add-port=443/tcp --zone=public --permanent
        firewall-cmd --add-port=80/tcp --zone=public --permanent
        firewall-cmd --reload

# Play 2: Deploy applications and cluster services FROM LOCAL MACHINE
- name: Deploy Kubernetes Manifests
  hosts: localhost
  connection: local
  tasks:
    - name: Set Kubeconfig fact for this play
      set_fact:
        k8s_auth_kubeconfig: "{{ playbook_dir }}/k3s_config"

    - name: Install cert-manager CustomResourceDefinitions
      kubernetes.core.k8s:
        state: present
        src: https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.crds.yaml

    - name: Create cert-manager namespace
      kubernetes.core.k8s:
        name: cert-manager
        api_version: v1
        kind: Namespace
        state: present

    - name: Add Jetstack Helm repo
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: https://charts.jetstack.io

    - name: Install or Upgrade cert-manager via Helm
      kubernetes.core.helm:
        name: cert-manager
        chart_ref: jetstack/cert-manager
        release_namespace: cert-manager
        chart_version: v1.14.4
        values:
          installCRDs: false

    - name: Deploy Brewsource MCP application using Kustomize
      kubernetes.core.k8s:
        state: present
        kustomization: https://github.com/CharlRitter/brewsource-mcp/tree/main/k8s/prod
