apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brewsource-mcp-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - brewsource.charlritter.com
    secretName: brewsource-tls-secret
  rules:
  - host: "brewsource.charlritter.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: brewsource-mcp
            port:
              number: 8080
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: brewsource-mcp
            port:
              number: 8080
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: brewsource-mcp
            port:
              number: 8080
