apiVersion: apps/v1
kind: Deployment
metadata:
  name: brewsource-mcp
  namespace: brewsource-dev
  labels:
    app: brewsource-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brewsource-mcp
  template:
    metadata:
      labels:
        app: brewsource-mcp
    spec:
      containers:
      - name: app
        image: brewsource-mcp:dev
        env:
        - name: DATABASE_URL
          value: postgres://brewsource_user:brewsource_pass@postgres:5432/brewsource?sslmode=disable
        - name: REDIS_URL
          value: redis://redis:6379/0
        - name: LOG_LEVEL
          value: debug
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: brewsource-mcp
  namespace: brewsource-dev
spec:
  selector:
    app: brewsource-mcp
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
