apiVersion: apps/v1
kind: Deployment
metadata:
  name: brewsource-mcp
spec:
  template:
    spec:
      containers:
      - name: brewsource-mcp
        # Enable live reload for development
        env:
        - name: LOG_LEVEL
          value: "debug"
        # Remove resource limits for development
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits: {}
        # Add volume mount for live code changes (Tilt will handle this)
        volumeMounts:
        - name: source-code
          mountPath: /app/src
          readOnly: true
      volumes:
      - name: source-code
        emptyDir: {}
