apiVersion: v1
kind: ConfigMap
metadata:
  name: brewsource-config
  labels:
    app: brewsource-mcp
data:
  DATABASE_URL: "postgres://brewsource_user:brewsource_pass@postgres:5432/brewsource?sslmode=disable"
  REDIS_URL: "redis://redis:6379/0"
  PORT: "8080"
  LOG_LEVEL: "info"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: brewsource-mcp
  labels:
    app: brewsource-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brewsource-mcp
  template:
    metadata:
      labels:
        app: brewsource-mcp
    spec:
      containers:
      - name: brewsource-mcp
        securityContext:
          allowPrivilegeEscalation: false
        image: ghcr.io/charlritter/brewsource-mcp:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: brewsource-config
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: brewsource-mcp
  labels:
    app: brewsource-mcp
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: brewsource-mcp
