apiVersion: apps/v1
kind: Deployment
metadata:
  name: brewsource-mcp
spec:
  template:
    spec:
      containers:
      - name: brewsource-mcp
        env:
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
