name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  #================================================= Validation jobs =================================================#

  conventional-commits:
    name: Validate Conventional Commits
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install conventional commit checker
        run: npm install -g @commitlint/cli @commitlint/config-conventional

      - name: Validate PR title
        run: |
          echo "${{ github.event.pull_request.title }}" | npx commitlint

      - name: Validate commit messages
        run: |
          npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  check-version-bump:
    name: Check VERSION bump on PR to main
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Check if VERSION file changed
        run: |
          git fetch origin ${{ github.base_ref }}
          if git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -q '^VERSION$'; then
            echo "VERSION file was changed."
          else
            echo "ERROR: VERSION file must be bumped for PRs to main."
            exit 1
          fi

  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Lint
        run: make lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: testpassword
          POSTGRES_USER: testuser
          POSTGRES_DB: brewsource_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Set up test environment
        env:
          DATABASE_URL: postgresql://testuser:testpassword@localhost:5432/brewsource_test?sslmode=disable
        run: |
          # Wait for PostgreSQL to be ready
          until pg_isready -h localhost -p 5432 -U testuser; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Run tests
        env:
          DATABASE_URL: postgresql://testuser:testpassword@localhost:5432/brewsource_test?sslmode=disable
        run: go test -v -race -coverprofile=coverage.out ./...

      - name: Generate coverage report
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.html

      - name: Check coverage threshold
        run: |
          coverage=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
          echo "Current coverage: ${coverage}%"
          if (( $(echo "$coverage < 80" | bc -l) )); then
            echo "Coverage is below 80% threshold"
            exit 1
          fi

  security-scan:
    name: Security Scan & Dependency Vulnerability Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'

      - name: Security Scan
        run: make security

  #=============================================== Build & Release jobs ===============================================#

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [check-version-bump, lint, test, conventional-commits, security-scan]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Build application
        run: |
          mkdir -p app/bin
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o app/bin/brewsource-mcp ./app/cmd/server

      - name: Test binary execution
        run: |
          chmod +x app/bin/brewsource-mcp
          timeout 5s ./app/bin/brewsource-mcp -help || true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: brewsource-mcp-binary
          path: app/bin/brewsource-mcp

  create-pr-rfv-release:
    name: Create PR RFV Release
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        run: |
          VERSION=$(cat VERSION)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set lowercase repository name
        id: repo_lower
        run: echo "repo_lowercase=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      - name: Download build artifact
        uses: actions/download-artifact@v5
        with:
          name: brewsource-mcp-binary
          path: ./release-artifacts/

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (rfv)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.repo_lower.outputs.repo_lowercase }}:v${{ steps.get_version.outputs.version }}-rfv-${{ github.run_attempt }}
            ghcr.io/${{ steps.repo_lower.outputs.repo_lowercase }}:rfv-latest

      - name: Create tag for PR (rfv)
        run: |
          TAG="v${{ steps.get_version.outputs.version }}-rfv-${{ github.run_attempt }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $TAG
          git push origin $TAG

      - name: Create GitHub pre-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}-rfv-${{ github.run_attempt }}
          name: "Release v${{ steps.get_version.outputs.version }}-rfv-${{ github.run_attempt }}"
          prerelease: true
          generate_release_notes: true
          files: ./release-artifacts/brewsource-mcp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-main-release:
    name: Create Main Release
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        run: |
          VERSION=$(cat VERSION)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set lowercase repository name
        id: repo_lower
        run: echo "repo_lowercase=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      - name: Download build artifact
        uses: actions/download-artifact@v5
        with:
          name: brewsource-mcp-binary
          path: ./release-artifacts/

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (main)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.repo_lower.outputs.repo_lowercase }}:v${{ steps.get_version.outputs.version }}
            ghcr.io/${{ steps.repo_lower.outputs.repo_lowercase }}:latest
          # cache-from and cache-to removed due to unsupported driver on GitHub Actions

      - name: Create tag for main
        run: |
          TAG="v${{ steps.get_version.outputs.version }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $TAG
          git push origin $TAG

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: "Release v${{ steps.get_version.outputs.version }}"
          generate_release_notes: true
          files: ./release-artifacts/brewsource-mcp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
